### ISSUE TITLE
Class "WelcomeCardServiceProvider" not found after installing

### ISSUE THREAD

**Issue by majdghithan** [dcasia/nova-welcome-card#1]
![Screenshot 2023-10-12 at 16 34 30](https://github.com/dcasia/nova-welcome-card/assets/54972678/78aaffc8-9bf0-4202-adbb-2fbbd7e802aa)

**Comment by milewski** [comment]
Ooops... my bad fixed here: [v0.0.2](https://github.com/dcasia/nova-welcome-card/releases/tag/v0.0.2)
